grid_map:
    FREE_SPACE: 0
    OBSTACLE: 1

test_settings:
  - ['random32', 4]
  - ['random32', 8]
  - ['random32', 16]
  - ['random32', 32]
  - ['random32', 64]
  - ['random64', 4]
  - ['random64', 8]
  - ['random64', 16]
  - ['random64', 32]
  - ['random64', 64]
  - ['den312d', 4]
  - ['den312d', 8]
  - ['den312d', 16]
  - ['den312d', 32]
  - ['den312d', 64]
  - ['warehouse', 4]
  - ['warehouse', 8]
  - ['warehouse', 16]
  - ['warehouse', 32]
  - ['warehouse', 64]


max_timesteps:
  'random32': 256
  'random64': 256
  'den312d': 256
  'warehouse': 512

num_instances_per_test: 300
runtime_limit: 120